/**
 * On-chain compatibility contract test.
 *
 * The base64 payloads below are NOT hand-written fixtures: they are the exact
 * XDR emitted by the deployed Aegis contract, captured from the Soroban host
 * with:
 *
 *     cargo test dump_event_xdr -- --ignored --nocapture
 *
 * This suite is the seam between the Rust contract and the JS monitoring
 * service. If anyone changes an event's topics, field order or data format on
 * the contract side without updating the off-chain decoder, these tests fail -
 * which is exactly the silent-drift bug class that would otherwise only show up
 * against live RPC in production.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizeEvent } from '../src/events/normalize.js';
import { matchesFilter } from '../src/events/filter.js';
import { AlertEngine } from '../src/alerts/index.js';
import { AnalyticsEngine } from '../src/analytics/index.js';

// Addresses generated by the Soroban test host during the dump.
const ADMIN = 'CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4';
const USER1 = 'CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHK3M';
const USER2 = 'CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAITA4';

/** Verbatim host output: [label, topicsCsv, valueBase64] */
const ON_CHAIN = {
  init: {
    topic: ['AAAADwAAAAVhZWdpcwAAAA==', 'AAAADwAAAARpbml0'],
    value: 'AAAAEgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAg==',
  },
  wl_add: {
    topic: [
      'AAAADwAAAAVhZWdpcwAAAA==',
      'AAAADwAAAAZ3bF9hZGQAAA==',
      'AAAAEgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAw==',
    ],
    value: 'AAAAEgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAg==',
  },
  mint: {
    topic: [
      'AAAADwAAAAVhZWdpcwAAAA==',
      'AAAADwAAAARtaW50',
      'AAAAEgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAw==',
    ],
    value:
      'AAAAEAAAAAEAAAADAAAACgAAAAAAAAAAAAAAAAAAA+gAAAAKAAAAAAAAAAAAAAAAAAAD6AAAAAoAAAAAAAAAAAAAAAAAAAPo',
  },
  transfer: {
    topic: [
      'AAAADwAAAAVhZWdpcwAAAA==',
      'AAAADwAAAAh0cmFuc2Zlcg==',
      'AAAAEgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAw==',
      'AAAAEgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABA==',
    ],
    value: 'AAAACgAAAAAAAAAAAAAAAAAAAPo=',
  },
  yield: {
    topic: ['AAAADwAAAAVhZWdpcwAAAA==', 'AAAADwAAAAV5aWVsZAAAAA=='],
    value:
      'AAAAEAAAAAEAAAADAAAAEgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAoAAAAAAAAAAAAAAAAAAAAqAAAACgAAAAAAAAAAAAAAAAAAA+g=',
  },
};

function asEvent(name, ledger = 42) {
  const { topic, value } = ON_CHAIN[name];
  return normalizeEvent({
    type: 'contract',
    ledger: String(ledger),
    ledgerClosedAt: '2026-07-28T00:00:00Z',
    contractId: 'CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2KM',
    id: `${name}-${ledger}`,
    pagingToken: `${name}-${ledger}`,
    inSuccessfulContractCall: true,
    topic,
    value,
  });
}

test('real init event decodes to the admin address', () => {
  const event = asEvent('init');
  assert.equal(event.protocol, 'aegis');
  assert.equal(event.action, 'init');
  assert.equal(event.fields.admin, ADMIN);
});

test('real whitelist event decodes both the indexed user and the admin', () => {
  const event = asEvent('wl_add');
  assert.equal(event.action, 'wl_add');
  assert.equal(event.fields.user, USER1, 'user is an indexed topic');
  assert.equal(event.fields.admin, ADMIN, 'admin is the data payload');
  assert.deepEqual(event.subjects, [USER1, ADMIN]);
});

test('real mint event decodes amount, running balance and total supply', () => {
  const event = asEvent('mint');
  assert.equal(event.action, 'mint');
  assert.equal(event.fields.to, USER1);
  assert.equal(event.fields.amount, 1000n);
  assert.equal(event.fields.newBalance, 1000n);
  assert.equal(event.fields.totalSupply, 1000n);
});

test('real transfer event decodes both counterparties and the amount', () => {
  const event = asEvent('transfer');
  assert.equal(event.action, 'transfer');
  assert.equal(event.fields.from, USER1);
  assert.equal(event.fields.to, USER2);
  assert.equal(event.fields.amount, 250n);
  assert.deepEqual(event.subjects, [USER1, USER2]);
});

test('real yield event decodes admin, amount and supply', () => {
  const event = asEvent('yield');
  assert.equal(event.action, 'yield');
  assert.equal(event.fields.admin, ADMIN);
  assert.equal(event.fields.amount, 42n);
  assert.equal(event.fields.totalSupply, 1000n);
});

test('every real event is namespaced so a single RPC filter captures the protocol', () => {
  for (const name of Object.keys(ON_CHAIN)) {
    const event = asEvent(name);
    assert.equal(event.topics[0], 'aegis', `${name} must be namespaced`);
    assert.equal(event.topics[1], name === 'wl_add' ? 'wl_add' : name);
    assert.ok(event.topics.length <= 4, 'Soroban allows at most 4 topics');
  }
});

test('filters work against real on-chain payloads', () => {
  const transfer = asEvent('transfer');
  assert.ok(matchesFilter(transfer, { action: 'transfer', address: USER2 }));
  assert.ok(matchesFilter(transfer, { minAmount: 250n }));
  assert.ok(!matchesFilter(transfer, { minAmount: 251n }));
  assert.ok(matchesFilter(transfer, { topicMatch: ['aegis', 'transfer', USER1, USER2] }));
});

test('alerts fire against real on-chain payloads', async () => {
  const engine = new AlertEngine();
  engine.addRule({
    name: 'mint-watch',
    pattern: 'threshold',
    filter: { action: 'mint' },
    gte: 1000n,
  });
  const fired = await engine.process(asEvent('mint'));
  assert.equal(fired.length, 1);
  assert.equal(fired[0].details.value, '1000');
});

test('analytics aggregate a real on-chain lifecycle correctly', () => {
  const analytics = new AnalyticsEngine();
  analytics.record(asEvent('init', 1));
  analytics.record(asEvent('wl_add', 2));
  analytics.record(asEvent('mint', 3));
  analytics.record(asEvent('transfer', 4));
  analytics.record(asEvent('yield', 5));

  const snap = analytics.snapshot();
  assert.equal(snap.totals.events, 5);
  assert.equal(snap.totals.minted, '1000');
  assert.equal(snap.totals.transferred, '250');
  assert.equal(snap.totals.yielded, '42');
  assert.equal(snap.totals.whitelisted, 1);
  assert.equal(snap.totals.uniqueAddresses, 3);
});

test('the simulator reproduces the exact on-chain topic encoding', async () => {
  // Guards the test double against drifting from real host output.
  const { build } = await import('../src/simulator.js');
  const simulated = build.transfer(USER1, USER2, 250n, { ledger: 42 });
  assert.deepEqual(simulated.topic, ON_CHAIN.transfer.topic);
  assert.equal(simulated.value, ON_CHAIN.transfer.value);
});
